# Generated by Django 2.2.27 on 2022-02-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
